on: 
    issues: 
        types: opened
jobs:
  node_job:
    runs-on: ubuntu-latest
    name: A node job to test
    steps:
      - name: Execution
        uses: Plinkie03/tryforge-theme-action@v1.0993
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}